import { Link } from "react-router-dom";
import { FeatureCard, PropertyCard } from "../components/Cards";
import { features, properties } from "../data/listings";

export default function Home() { return <>
  <section className="hero"><div className="container hero-grid"><div><p className="eyebrow">Your next chapter starts here</p><h1>Find a place<br /><i>that feels like you.</i></h1><p className="lead">Curated homes, trusted local expertise, and a refreshingly human way to find your place.</p><Link className="button" to="/properties">Browse properties <span>→</span></Link><div className="hero-stats"><div><b>1,200+</b><span>Homes matched</span></div><div><b>18 yrs</b><span>Local expertise</span></div></div></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1600585152915-d208bec867a1?auto=format&fit=crop&w=1400&q=90" alt="Modern home exterior" /><div className="hero-note"><span>A home is more than an address.</span><b>It is where life<br />takes shape.</b></div></div></div></section>
  <section className="section container"><div className="section-heading"><div><p className="eyebrow">The HomeNest difference</p><h2>Every detail,<br /><i>considered.</i></h2></div><p>We combine personal attention with clear, expert guidance—so finding home feels less like a search and more like a discovery.</p></div><div className="feature-grid">{features.map((feature) => <FeatureCard key={feature[0]} feature={feature} />)}</div></section>
  <section className="featured"><div className="container"><div className="section-heading compact"><div><p className="eyebrow">Handpicked for you</p><h2>Homes with<br /><i>good bones.</i></h2></div><Link className="text-link" to="/properties">See all properties →</Link></div><div className="property-grid">{properties.slice(0, 3).map((property) => <PropertyCard key={property.id} property={property} />)}</div></div></section>
  <section className="benefit"><div className="container benefit-grid"><img src="https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=85" alt="Warm modern living room" /><div><p className="eyebrow">More than a move</p><h2>Guidance for<br /><i>the whole journey.</i></h2><p className="lead">From your first viewing to the final signature, our people bring clarity, care, and an unwavering focus on what matters to you.</p><Link className="text-link" to="/about">Meet our team →</Link></div></div></section>
</>; }
