import { useState } from "react";
import { PropertyCard } from "../components/Cards";
import { properties, testimonials } from "../data/listings";
const faqs = [["How do I book a property viewing?", "Choose a property you love and use our contact form to share a preferred date. An advisor will confirm your visit shortly."], ["Are all listings verified?", "Yes. We personally review each listing and check its available ownership and property documentation."], ["Can HomeNest help with a home loan?", "Absolutely. Our finance partners can help you compare loan options tailored to your purchase."], ["Do you also manage rental properties?", "Yes. We assist tenants and owners with residential as well as commercial rentals and leases."]];
export default function Properties() { const [filter, setFilter] = useState("All"); const [activeFaq, setActiveFaq] = useState(null); const visible = filter === "All" ? properties : properties.filter((item) => item.type === filter); return <>
  <section className="page-intro container"><p className="eyebrow">Explore our collection</p><h1>Find your next<br /><i>favourite place.</i></h1><p className="lead">A selection of distinctive homes and spaces, chosen for the way you want to live.</p></section>
  <section className="container listing-section"><div className="filter-bar"><span>Showing {visible.length} properties</span><div>{["All", "Buy", "Rent", "Lease"].map((item) => <button className={filter === item ? "selected" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div></div><div className="property-grid all-properties">{visible.map((property) => <PropertyCard key={property.id} property={property} />)}</div></section>
  <section className="testimonials"><div className="container"><p className="eyebrow">In their words</p><h2>Made to feel<br /><i>right at home.</i></h2><div className="testimonial-grid">{testimonials.map(([quote, name, detail]) => <article key={name}><span>“</span><p>{quote}</p><b>{name}</b><small>{detail}</small></article>)}</div></div></section>
  <section className="section container faq"><div><p className="eyebrow">Questions, answered</p><h2>Good to<br /><i>know.</i></h2></div><div>{faqs.map(([question, answer], index) => <article className={activeFaq === index ? "faq-item active" : "faq-item"} key={question}><button onClick={() => setActiveFaq(activeFaq === index ? null : index)}><span>{question}</span><b>{activeFaq === index ? "−" : "+"}</b></button>{activeFaq === index && <p>{answer}</p>}</article>)}</div></section>
</>; }
